---
kind: pipeline
name: default

steps:
- name: build
  image: cryptocom/chain-test:latest
  pull: if-not-exists
  commands:
  - export BUILD_MODE=mock
  - export CARGO_HOME=$PWD/drone/cargo
  - export CARGO_TARGET_DIR=$PWD/drone/target
  - ./docker/build.sh

- name: unit-tests
  image: cryptocom/chain-test:latest
  pull: if-not-exists
  commands:
  - export BUILD_MODE=mock
  - export CARGO_HOME=$PWD/drone/cargo
  - export CARGO_TARGET_DIR=$PWD/drone/target
  - cargo test

- name: integration-tests
  image: cryptocom/chain-test:latest
  pull: if-not-exists
  commands:
  - export BUILD_MODE=mock
  - export CARGO_TARGET_DIR=$PWD/drone/target
  - export PYTHON_VENV_DIR=$PWD/drone/venv
  - ./integration-tests/run.sh

- name: multinode-tests
  image: cryptocom/chain-test:latest
  pull: if-not-exists
  commands:
  - export BUILD_MODE=mock
  - export CARGO_TARGET_DIR=$PWD/drone/target
  - export PYTHON_VENV_DIR=$PWD/drone/venv
  - ./integration-tests/run_multinode.sh

- name: teardown
  image: cryptocom/chain-test:latest
  pull: if-not-exists
  commands:
  - export BUILD_MODE=mock
  - ./integration-tests/cleanup.sh
  when:
    status:
      - success
      - failure

- name: coverage
  image: cryptocom/chain-test:latest
  pull: if-not-exists
  environment:
    CODECOV_TOKEN:
      from_secret: CODECOV_TOKEN
  commands:
  - export CARGO_TARGET_DIR=$PWD/drone/target
  - export CARGO_HOME=$PWD/drone/cargo
  - cargo install cargo-kcov
  - sed 's/"chain-tx-enclave/#"chain-tx-enclave/g' -i Cargo.toml;
  - cargo kcov --all;
  - bash <(curl -s https://codecov.io/bash);

trigger:
  branch:
  - master
  - staging
  - trying
  event:
  - push
