[workspace]

members = [
    "chain-abci",
    "chain-core",
    "chain-tx-filter",
    "chain-tx-validation",
    "client-cli",
    "client-common",
    "client-core",
    "client-network",
    "client-rpc",
    "test-common",
    "dev-utils",
    "enclave-protocol",
    "sgx-wrapper",
    "chain-tx-enclave/enclave-t-common",
    "chain-tx-enclave/enclave-u-common",
    "chain-tx-enclave/enclave-macro",
    "chain-tx-enclave/tx-validation/app",
    "chain-tx-enclave/tx-validation/enclave",
    "chain-tx-enclave/tx-query/app",
    "chain-tx-enclave/tx-query/enclave"
]
